# Generated by Django 2.1.5 on 2023-05-20 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(verbose_name='学号')),
                ('student_class', models.CharField(max_length=8, verbose_name='班级')),
                ('name', models.CharField(max_length=8, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', models.SmallIntegerField(choices=[(0, '男'), (1, '女')], verbose_name='性别')),
                ('score', models.CharField(max_length=6, verbose_name='Python Web成绩')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, unique=True, verbose_name='姓名')),
                ('subjects', models.CharField(max_length=16, verbose_name='科目')),
            ],
        ),
        migrations.AddField(
            model_name='studentdata',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.TeacherData', to_field='name', verbose_name='任课老师'),
        ),
    ]
